### ISSUE TITLE
build issue: std::reduce

### ISSUE THREAD

**Issue by jimfranssen** [linville/gray16lib#1]
I am trying to build the code on ubuntu using Qt5.13.0 in combination with gcc-9 and g++-9.
All compiles well except line 119 in image_histogram_widget.cpp

I get the error: no matching function for call to ‘reduce(QVector<int>::const_iterator, QVector<int>::const_iterator)'

Code on line 119 |  int sum = std::reduce(histogram.constBegin(), histogram.constEnd());

<img width="1164" alt="issue" src="https://user-images.githubusercontent.com/51799662/59459873-21476180-8e1e-11e9-880b-f4144fec2af8.png">

std::reduce takes a minimum of 3 arguments, you are just providing 2

Can you please help resolving this issue.

**Comment by linville** [comment]
The standard does have a [two argument version](https://en.cppreference.com/w/cpp/algorithm/reduce) and this works in Xcode 10.2. Might be an issue with the Intel Parallel STL implementation; I haven't started peeling the onion back.

As a workaround, `std::accumulate` will also work.

```diff
   // Draw Cumulative Value
-  int sum = std::reduce(histogram.constBegin(), histogram.constEnd());
+  int sum = std::accumulate(histogram.constBegin(), histogram.constEnd(), 0);
   const auto sumScale = static_cast<double> (height) / static_cast<double> (sum);
```

**Comment by jimfranssen** [comment]
int sum = std::accumulate(histogram.constBegin(), histogram.constEnd(), 0); does the trick

Thanks

**Comment by linville** [comment]
Re-opening just to ensure I formally correct this since `std::reduce` isn't widely supported yet.

The code should use the feature macro `__cpp_lib_parallel_algorithm` (and possibly compiler defines to identify if it's being compiled by Apple Clang which implements `std::reduce` but doesn't set feature macros) to use the `std::reduce` otherwise it should use `std::accumulate`.
